### ISSUE TITLE
confluence

### ISSUE THREAD

**Issue by anacrolix** [pojntfx/htorrent#3]
I just found this, digging through some GitHub stuff. How does this differ from https://github.com/anacrolix/confluence? Cheers

**Comment by pojntfx** [comment]
Not too much! ~~It was written before confluence existed~~, and is now mostly in use in [Multiplex](https://github.com/pojntfx/multiplex) :)

**Comment by anacrolix** [comment]
confluence has been around since 2016, but that's not important. Cool project.
